language: cpp
sudo: required
compiler:
  - gcc
services:
  - docker
# Distro versions
env:
  global:
    - MAKEFLAGS="-j 2"
  matrix:
    - BUILD_TARGET=ubuntu16.04 # Ubuntu16.04
    - BUILD_TARGET=ubuntu18.04 # Ubuntu18.04
    - BUILD_TARGET=ubuntu18.10 # Ubuntu18.10
    - BUILD_TARGET=arch # Arch Linux
    - WITH_JAVA=true
    - WITH_JAVA=false
script:
  - docker run -v $(pwd):/build augugrumi/astaire-dockerbuilds:$BUILD_TARGET
