language: cpp
sudo: required
compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libboost-all-dev
      - libpcap-dev
      - libtins-dev

before_script:
  - cd /tmp/ && wget https://github.com/Augugrumi/libviface/releases/download/v1.1.1/libviface_1.0.0.deb -O libviface_1.0.0.deb && sudo dpkg -i libviface_1.0.0.deb && cd -
  - aclocal -I m4 --install && autoconf && automake --add-missing
