language: cpp
sudo: required
compiler:
  - gcc
services:
  - docker
# Distro versions
env:
  global:
    - MAKEFLAGS="-j 2"
  matrix:
    - BUILD_TARGET=ubuntu16.04 WITH_JAVA=true # Ubuntu16.04
    - BUILD_TARGET=ubuntu16.04 WITH_JAVA=false # Ubuntu16.04
    - BUILD_TARGET=ubuntu18.04 WITH_JAVA=true # Ubuntu18.04
    - BUILD_TARGET=ubuntu18.04 WITH_JAVA=false # Ubuntu18.04
    - BUILD_TARGET=ubuntu18.10 WITH_JAVA=true # Ubuntu18.10
    - BUILD_TARGET=ubuntu18.10 WITH_JAVA=false # Ubuntu18.10
    - BUILD_TARGET=arch WITH_JAVA=true # Arch Linux
    - BUILD_TARGET=arch WITH_JAVA=false # Arch Linux
script:
  - docker run -v $(pwd):/build augugrumi/astaire-dockerbuilds:$BUILD_TARGET
