FROM ubuntu:16.04

LABEL maintainer="poloniodavide@gmail.com"

RUN apt-get update && apt-get install -y \
    autotools-dev \
    automake \
    autoconf \
    build-essential \
    wget \
    libboost-all-dev \
    libpcap-dev \
    libssl-dev \
    cmake \
    git && \
    wget https://github.com/Augugrumi/libviface/releases/download/v1.1.1/libviface_1.0.0.deb && \
    dpkg -i libviface_1.0.0.deb

RUN git clone https://github.com/mfontanini/libtins.git && \
    cd libtins && \
    mkdir build && \
    cd build && \
    cmake ../ -DLIBTINS_ENABLE_CXX11=1 && \
    make && \
    make install && \
    ldconfig

RUN mkdir -p /build/
WORKDIR /build/

COPY . /build/

RUN aclocal -I m4 --install && \
    autoconf && \
    automake --add-missing && \
    ./configure && \
    make
